import { resolve } from 'node:path'
import { test, expect } from '@playwright/test'

const screenshotRoot = resolve('../../research/screenshots/workbench-mvp')

test.beforeEach(async ({ context }) => {
  await context.route('**/*', async (route) => {
    const url = new URL(route.request().url())
    if (url.hostname === '127.0.0.1') return route.continue()
    return route.abort('blockedbyclient')
  })
})

test.afterEach(async ({ page }) => {
  await page.evaluate(() => fetch('/__e2e_shutdown', { method: 'POST' })).catch(() => {})
})

test('create, persist and manage synthetic project work items on desktop and mobile', async ({ page, browserName }) => {
  test.setTimeout(120_000)
  const crossOriginBootstrap = await page.request.post('/api/v1/session/bootstrap', {
    data: {},
    headers: { Origin: 'https://attacker.example' },
  })
  expect(crossOriginBootstrap.status()).toBe(403)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/projects')
  await expect(page.getByRole('heading', { name: '项目工作台' })).toBeVisible()
  await expect(page.locator('.sidebar__brand')).toContainText('DDUP')
  await expect(page.locator('.sidebar__nav-group-label')).toHaveText(/媒体数据/)
  await expect(page.locator('.sidebar__nav-item--child')).toHaveText(/抖音数据/)
  await expect(page.getByText('建立第一个项目')).toBeVisible()

  await page.getByRole('button', { name: '新建项目', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: '建立新的项目空间' })).toBeVisible()
  await page.getByLabel('项目名称').fill('合成上下文研究项目')
  await page.getByLabel('目标与说明').fill('完全虚构，用于验证项目创建、持久化与状态迁移。')
  await page.getByLabel('项目模板').selectOption('research')
  await page.getByLabel('开始日期').fill('2026-08-24')
  await page.getByLabel('目标日期').fill('2026-12-31')
  await page.getByRole('button', { name: '创建项目', exact: true }).click()

  const card = page.getByRole('article').filter({ hasText: '合成上下文研究项目' })
  await expect(card).toBeVisible()
  await expect(card.getByText('草稿', { exact: true })).toBeVisible()
  await expect(page.getByText('项目已创建并持久化。刷新或重启后仍会保留。')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'project-workbench-desktop.png'), fullPage: true })

  await page.reload()
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await page.getByLabel('项目名称').fill('合成上下文研究项目 · 已更新')
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  const updatedCard = page.getByRole('article').filter({ hasText: '合成上下文研究项目 · 已更新' })
  await expect(updatedCard).toBeVisible()
  await updatedCard.getByRole('button', { name: '启动项目', exact: true }).click()
  await expect(updatedCard.getByText('进行中', { exact: true })).toBeVisible()

  await updatedCard.getByRole('button', { name: '打开工作项', exact: true }).click()
  const workPanel = page.getByLabel('合成上下文研究项目 · 已更新 工作项')
  await expect(workPanel.getByRole('heading', { name: '合成上下文研究项目 · 已更新', exact: true })).toBeVisible()
  const milestoneForm = workPanel.getByRole('form', { name: '新建里程碑' })
  await milestoneForm.getByLabel('里程碑名称').fill('完成合成开题材料')
  await milestoneForm.getByLabel('目标日期').fill('2026-10-30')
  await milestoneForm.getByRole('button', { name: '保存里程碑' }).click()
  await expect(workPanel.getByLabel('里程碑列表').getByText('完成合成开题材料', { exact: true })).toBeVisible()

  const taskForm = workPanel.getByRole('form', { name: '新建任务' })
  await taskForm.getByLabel('任务名称').fill('整理虚构研究问题清单')
  await taskForm.getByLabel('优先级').selectOption('high')
  await taskForm.getByLabel('目标日期').fill('2026-09-30')
  await taskForm.getByLabel('关联里程碑').selectOption({ label: '完成合成开题材料' })
  await taskForm.getByRole('button', { name: '保存任务' }).click()
  const taskRow = workPanel.getByRole('article').filter({ hasText: '整理虚构研究问题清单' })
  await expect(taskRow).toBeVisible()
  await taskRow.getByRole('button', { name: '纳入计划' }).click()
  await expect(taskRow.getByText('已计划', { exact: true })).toBeVisible()
  await taskRow.getByRole('button', { name: '开始', exact: true }).click()
  await expect(taskRow.getByText('进行中', { exact: true })).toBeVisible()
  await taskRow.getByRole('button', { name: '完成', exact: true }).click()
  await expect(taskRow.getByText('已完成', { exact: true })).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'project-work-items-desktop.png'), fullPage: true })

  const discussionPanel = workPanel.getByLabel('讨论与决策')
  const discussionForm = discussionPanel.getByRole('form', { name: '新建讨论' })
  await discussionForm.getByLabel('聚焦问题').fill('下一阶段是否继续合成研究路线？')
  await discussionForm.getByRole('button', { name: '建立讨论' }).click()
  await expect(discussionPanel.getByText('聚焦讨论已建立。当前只记录人工输入，不调用 AI。')).toBeVisible()
  const entryForm = discussionPanel.getByRole('form', { name: '追加讨论记录' })
  await entryForm.getByLabel('补充观点或依据').fill('虚构验证已证明状态机和持久化路径可用。')
  await entryForm.getByRole('button', { name: '保存记录' }).click()
  await expect(discussionPanel.getByText('虚构验证已证明状态机和持久化路径可用。')).toBeVisible()

  const conversionForm = discussionPanel.getByRole('form', { name: '形成决策与任务' })
  await conversionForm.getByLabel('决策标题').fill('继续合成研究路线')
  await conversionForm.getByLabel('决定内容').fill('继续使用完全虚构的数据完成下一阶段验证。')
  await conversionForm.getByLabel('原因与取舍').fill('先证明闭环，再评审真实数据接入。')
  await conversionForm.getByRole('textbox', { name: '后续任务', exact: true }).fill('补充合成验收场景')
  await conversionForm.getByLabel('优先级').selectOption('high')
  await conversionForm.getByLabel('任务日期').fill('2026-08-24')
  await conversionForm.getByLabel('关联里程碑').selectOption({ label: '完成合成开题材料' })
  await conversionForm.getByLabel('我已核对决定和后续任务，确认写入长期项目记录。').check()
  await conversionForm.getByRole('button', { name: '确认形成决策并创建任务' }).click()
  await expect(discussionPanel.getByText('已按你的明确确认形成正式决策，并在同一事务创建后续任务。')).toBeVisible()
  await expect(discussionPanel.getByText('继续合成研究路线', { exact: true })).toBeVisible()
  await expect(workPanel.getByLabel('任务列表').getByText('补充合成验收场景', { exact: true })).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'project-decision-flow-desktop.png'), fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.getByRole('heading', { name: '项目工作台' })).toBeVisible()
  await expect(updatedCard).toBeVisible()
  await updatedCard.getByRole('button', { name: '打开工作项', exact: true }).click()
  await expect(workPanel.getByText('整理虚构研究问题清单', { exact: true })).toBeVisible()
  await expect(workPanel.getByText('继续合成研究路线', { exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: resolve(screenshotRoot, 'project-workbench-mobile.png'), fullPage: true })

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/inbox')
  await expect(page.getByRole('heading', { name: '通用收件箱' })).toBeVisible()
  const captureForm = page.getByLabel('快速捕获')
  await captureForm.getByLabel('标题').fill('合成研究灵感')
  await captureForm.getByLabel('内容').fill('完全虚构：评估下一阶段的本地恢复路径。')
  await captureForm.getByLabel('关联项目（可选）').selectOption({ label: '合成上下文研究项目 · 已更新' })
  await captureForm.getByRole('button', { name: '放入收件箱' }).click()
  await expect(page.getByText('已进入本地收件箱；不会自动调用 AI、抓取网页或写入长期知识。')).toBeVisible()

  await captureForm.getByRole('button', { name: '链接' }).click()
  await captureForm.getByLabel('标题').fill('合成参考链接')
  await captureForm.getByLabel('http/https 链接').fill('https://example.com/synthetic-reference')
  await captureForm.getByRole('button', { name: '放入收件箱' }).click()
  const textCapture = page.getByRole('article').filter({ hasText: '合成研究灵感' })
  await expect(textCapture).toBeVisible()
  await expect(page.getByRole('article').filter({ hasText: '合成参考链接' })).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'capture-inbox-desktop.png'), fullPage: true })
  await textCapture.getByRole('button', { name: '完成整理' }).click()
  await page.getByRole('tab', { name: '已处理' }).click()
  await expect(page.getByRole('article').filter({ hasText: '合成研究灵感' })).toBeVisible()

  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.waitForTimeout(350)
  await page.screenshot({ path: resolve(screenshotRoot, 'capture-inbox-mobile.png'), fullPage: true })

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '今日', exact: true })).toBeVisible()
  const dailyTask = page.getByLabel('候选任务').getByRole('article').filter({ hasText: '补充合成验收场景' })
  await expect(dailyTask).toBeVisible()
  await dailyTask.getByRole('checkbox', { name: '选择 补充合成验收场景 为今日重点' }).check()
  await page.getByRole('button', { name: '保存今日重点' }).click()
  await expect(page.getByText('今日重点已保存；这里只引用项目任务，不复制任务状态。')).toBeVisible()
  await dailyTask.getByRole('button', { name: '开始', exact: true }).click()
  await expect(dailyTask.getByText('进行中', { exact: true })).toBeVisible()
  await dailyTask.getByRole('button', { name: '完成', exact: true }).click()
  await expect(dailyTask.getByText('已完成', { exact: true })).toBeVisible()
  const reviewForm = page.getByRole('form', { name: '保存日终复盘' })
  await reviewForm.getByLabel('今日总结').fill('完成完全虚构的项目闭环验收。')
  await reviewForm.getByLabel('完成与收获').fill('项目、讨论、任务和收件箱状态一致。')
  await reviewForm.getByLabel('阻塞与原因').fill('真实数据与外部连接仍未授权。')
  await reviewForm.getByLabel('明日第一步').fill('评审下一阶段知识库范围。')
  await reviewForm.getByRole('button', { name: '保存复盘' }).click()
  await expect(page.getByText('日终复盘已保存为你的明确记录，不由 AI 自动改写。')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'today-review-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.waitForTimeout(350)
  await page.screenshot({ path: resolve(screenshotRoot, 'today-review-mobile.png'), fullPage: true })

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/context')
  await expect(page.getByRole('heading', { name: '个人上下文知识库' })).toBeVisible()
  await expect(page.getByText('尚无受控来源')).toBeVisible()
  const sourceForm = page.getByRole('form', { name: '导入 Markdown 来源' })
  await sourceForm.getByLabel('Markdown 文件').setInputFiles({
    name: 'synthetic-context-evidence.md',
    mimeType: 'text/markdown',
    buffer: Buffer.from('# 合成上下文证据包\n\n完全虚构的受控证据，用于验证来源定位、项目过滤与全文检索。'),
  })
  await sourceForm.getByLabel('关联项目（可选）').selectOption({ label: '合成上下文研究项目 · 已更新' })
  await sourceForm.getByRole('button', { name: '导入并建立索引' }).click()
  await expect(page.getByText('Markdown 已写入受控来源目录，并建立可追溯 SourceVersion 与全文索引。')).toBeVisible()
  await expect(page.getByText('合成上下文证据包', { exact: true })).toBeVisible()

  const packageForm = page.getByRole('form', { name: '创建上下文篮' })
  await packageForm.getByLabel('名称').fill('合成方法论论证篮')
  await packageForm.getByLabel('使用目的').fill('聚焦验收固定证据范围与版本追溯。')
  await packageForm.getByRole('button', { name: '创建上下文篮' }).click()
  await expect(page.getByText('已创建空的显式上下文篮；不会自动纳入任何知识。')).toBeVisible()
  await expect(page.getByText('这是一个空篮')).toBeVisible()

  const contextSearch = page.getByRole('form', { name: '统一上下文检索' })
  await contextSearch.getByLabel('检索关键词').fill('完全虚构')
  await contextSearch.getByRole('button', { name: '执行检索' }).click()
  const documentResult = page.locator('.context-results article').filter({ hasText: '合成上下文证据包' })
  await expect(documentResult).toBeVisible()
  await expect(documentResult.getByText(/原文字符/)).toBeVisible()
  await documentResult.getByRole('button', { name: '打开原文' }).click()
  await expect(page.getByRole('complementary', { name: '固定原文预览' })).toContainText('完全虚构的受控证据')
  await page.getByRole('button', { name: '关闭原文预览' }).click()
  await documentResult.getByRole('button', { name: '加入上下文篮' }).click()
  await expect(documentResult.getByRole('button', { name: '已在篮中' })).toBeDisabled()
  await expect(page.locator('.context-package-items').getByText('合成上下文证据包')).toBeVisible()
  await expect(page.getByText('已加入当前上下文篮，范围和版本均已锁定。')).toBeVisible()
  await expect(page.getByText(/过滤在正文返回前执行/).first()).toBeVisible()

  await contextSearch.getByLabel('检索关键词').fill('合成上下文研究项目')
  await contextSearch.getByRole('button', { name: '执行检索' }).click()
  const projectResult = page.locator('.context-results article')
    .filter({ has: page.getByText('项目', { exact: true }) })
    .filter({ has: page.getByText('合成上下文研究项目 · 已更新', { exact: true }) })
  await expect(projectResult).toBeVisible()
  await projectResult.getByRole('button', { name: '加入上下文篮' }).click()
  await expect(page.locator('.context-package-items').getByText('合成上下文研究项目 · 已更新')).toBeVisible()
  const answerCheck = page.getByRole('form', { name: '记录回答安全检查' })
  await answerCheck.getByPlaceholder('输入需要由当前上下文支撑的问题…').fill('这条完全虚构的证据说明了什么？')
  await answerCheck.getByRole('button', { name: '记录安全检查' }).click()
  await expect(page.getByText('证据复核通过，可生成保守引用回答')).toBeVisible()
  await expect(page.getByText('上下文 v3 · 1 条固定引用 · 复核通过 · 本地提取式运行时已就绪')).toBeVisible()
  await page.getByRole('button', { name: '生成引用回答' }).click()
  await expect(page.getByText('回答已生成并通过逐句证据校验')).toBeVisible()
  await expect(page.locator('.context-final-answer')).toContainText('完全虚构的受控证据')
  const draftValidation = page.getByRole('form', { name: '提取式逐句预检' })
  await draftValidation.getByPlaceholder('粘贴一条需要核对的候选句…').fill('完全虚构的受控证据')
  await draftValidation.getByRole('button', { name: '核对原文' }).click()
  await expect(page.getByText('原文定位通过')).toBeVisible()
  await expect(page.getByText('所有候选句都能在所标注的固定引用范围内原样定位。')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'context-library-desktop.png'), fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.waitForTimeout(350)
  await page.screenshot({ path: resolve(screenshotRoot, 'context-library-mobile.png'), fullPage: true })
  await draftValidation.getByPlaceholder('粘贴一条需要核对的候选句…').fill('这是一条没有原样出现的合成推断。')
  await draftValidation.getByRole('button', { name: '核对原文' }).click()
  await expect(page.getByText('未找到原样文本')).toBeVisible()

  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/runtime')
  await expect(page.getByRole('heading', { name: 'AI 运行中心' })).toBeVisible()
  await expect(page.getByText('尚无运行记录')).toBeVisible()
  const runtimeForm = page.getByRole('form', { name: '启动确定性运行' })
  await runtimeForm.getByLabel('本次目标').fill('验证合成任务候选、检查点与审批分离。')
  await runtimeForm.getByRole('checkbox', { name: /同时生成一个待确认候选/ }).check()
  await runtimeForm.getByLabel('目标项目').selectOption({ label: '合成上下文研究项目 · 已更新' })
  await runtimeForm.getByLabel('任务标题').fill('复核合成 Runtime 验收证据')
  await runtimeForm.getByLabel('优先级').selectOption('high')
  await runtimeForm.getByLabel('任务说明').fill('完全虚构，用于验证候选不会跳过审批直接写入项目。')
  await runtimeForm.getByRole('button', { name: '启动运行' }).click()
  await expect(page.getByText('运行已完成，任务仍是待确认候选，尚未写入项目。')).toBeVisible()
  await expect(page.getByText('运行已完成', { exact: true })).toBeVisible()
  await expect(page.getByText('检查点').first()).toBeVisible()
  let candidateCard = page.getByRole('article').filter({ hasText: '复核合成 Runtime 验收证据' })
  await expect(candidateCard).toBeVisible()
  await candidateCard.getByRole('button', { name: '申请 L2 审批' }).click()
  await expect(page.getByText('已建立 24 小时有效的 L2 审批，批准本身不会写入任务。')).toBeVisible()
  candidateCard = page.getByRole('article').filter({ hasText: '复核合成 Runtime 验收证据' })
  await candidateCard.getByRole('button', { name: '批准范围' }).click()
  await expect(page.getByText('候选已批准，但仍未写入项目；请再次选择应用。')).toBeVisible()
  candidateCard = page.getByRole('article').filter({ hasText: '复核合成 Runtime 验收证据' })
  await candidateCard.getByRole('button', { name: '应用为任务' }).click()
  await expect(page.getByText('候选已通过审批范围复核，并作为对应业务对象写入一次。')).toBeVisible()
  candidateCard = page.getByRole('article').filter({ hasText: '复核合成 Runtime 验收证据' })
  await candidateCard.getByRole('button', { name: '安全撤销' }).click()
  await expect(page.getByText('刚应用且未发生后续变更的对象已安全撤销，审计记录继续保留。')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'runtime-center-desktop.png'), fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.waitForTimeout(350)
  await expect(page.getByRole('heading', { name: 'AI 运行中心' })).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'runtime-center-mobile.png'), fullPage: true })

  await page.goto('/')
  await page.keyboard.press('Control+k')
  const palette = page.getByRole('dialog', { name: '全局搜索' })
  await palette.getByLabel('搜索输入框').fill('完全虚构')
  await expect(palette.getByRole('button').filter({ hasText: '合成上下文证据包' })).toBeVisible()
  await palette.getByRole('button').filter({ hasText: '合成上下文证据包' }).click()
  await expect(page.getByRole('heading', { name: '个人上下文知识库' })).toBeVisible()
  await expect(page.locator('.context-results article').filter({ hasText: '合成上下文证据包' })).toBeVisible()

  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/projects')
  await page.getByRole('button', { name: '新建项目', exact: true }).first().click()
  await page.getByLabel('项目名称').fill('合成 AI 应用实验室')
  await page.getByLabel('目标与说明').fill('完全虚构，用于验证机会、指标评测与 Go/Stop 决策。')
  await page.getByLabel('项目模板').selectOption('ai_exploration')
  await page.getByRole('button', { name: '创建项目', exact: true }).click()
  await expect(page.getByRole('article').filter({ hasText: '合成 AI 应用实验室' })).toBeVisible()

  await page.getByRole('button', { name: '新建项目', exact: true }).first().click()
  await page.getByLabel('项目名称').fill('合成前沿雷达项目')
  await page.getByLabel('目标与说明').fill('完全虚构，用于验证可核验前沿信号和复查决定。')
  await page.getByLabel('项目模板').selectOption('frontier_tracking')
  await page.getByRole('button', { name: '创建项目', exact: true }).click()
  await expect(page.getByRole('article').filter({ hasText: '合成前沿雷达项目' })).toBeVisible()

  await page.getByRole('button', { name: '新建项目', exact: true }).first().click()
  await page.getByLabel('项目名称').fill('合成学习提升项目')
  await page.getByLabel('目标与说明').fill('完全虚构，用于验证学术英语练习、反馈和轻量习惯。')
  await page.getByLabel('项目模板').selectOption('learning')
  await page.getByRole('button', { name: '创建项目', exact: true }).click()
  await expect(page.getByRole('article').filter({ hasText: '合成学习提升项目' })).toBeVisible()

  await page.goto('/context')
  const radarSourceForm = page.getByRole('form', { name: '导入 Markdown 来源' })
  await radarSourceForm.getByLabel('Markdown 文件').setInputFiles({
    name: 'synthetic-frontier-evidence.md',
    mimeType: 'text/markdown',
    buffer: Buffer.from('# 合成前沿公告\n\n完全虚构：离线评测接口已经发布，但尚无长期稳定性证据。'),
  })
  await radarSourceForm.getByLabel('关联项目（可选）').selectOption({ label: '合成前沿雷达项目' })
  await radarSourceForm.getByRole('button', { name: '导入并建立索引' }).click()
  await expect(page.getByText('合成前沿公告', { exact: true })).toBeVisible()

  await page.goto('/professional')
  await expect(page.getByRole('heading', { name: '专业工作台', exact: true })).toBeVisible()
  await expect(page.getByText('当前是本地首版。')).toBeVisible()
  const researchWorkspace = page.getByLabel('科研工作台')
  const questionForm = researchWorkspace.getByRole('form', { name: '新建研究问题' })
  await questionForm.getByLabel('研究问题').fill('窗口化是否改善合成长文主题区分？')
  await questionForm.getByLabel('问题描述').fill('完全虚构：相邻主题可能产生错排。')
  await questionForm.getByLabel('假设').fill('固定窗口和重叠可以改善区分。')
  await questionForm.getByLabel('成功标准').fill('合成边界集 Top-1 达到 100%。')
  await questionForm.getByRole('button', { name: '保存研究问题' }).click()
  const questionCard = researchWorkspace.getByRole('article').filter({ hasText: '窗口化是否改善合成长文主题区分？' })
  await expect(questionCard).toBeVisible()
  await questionCard.getByRole('button', { name: '开始验证' }).click()
  await expect(questionCard.getByText('验证中', { exact: true })).toBeVisible()
  const experimentForm = questionCard.getByRole('form', { name: '新建研究实验' })
  await experimentForm.getByLabel('实验名称').fill('合成窗口边界实验')
  await experimentForm.getByLabel('方法').fill('在冻结的完全虚构边界集上比较固定窗口。')
  await experimentForm.getByLabel('变量与边界').fill('窗口 160 字符，重叠 40 字符。')
  await experimentForm.getByLabel('预期结果').fill('保持原文定位并达到目标。')
  await experimentForm.getByRole('button', { name: '保存实验' }).click()
  const resultForm = questionCard.getByRole('form', { name: '记录 合成窗口边界实验 结果' })
  await resultForm.getByLabel('结果摘要').fill('完全虚构：指标达到预设目标，定位保持一致。')
  await resultForm.getByLabel('实验决定').selectOption('continue')
  await resultForm.getByLabel('后续任务（可选）').fill('复核合成科研结论')
  await resultForm.getByRole('button', { name: '记录结果' }).click()
  await expect(questionCard.getByText('完全虚构：指标达到预设目标，定位保持一致。')).toBeVisible()
  const claimForm = questionCard.getByRole('form', { name: '记录研究主张' })
  await claimForm.getByLabel('研究主张').fill('合成窗口实验满足当前成功标准。')
  await claimForm.getByLabel('检索当前项目的受控来源').fill('完全虚构')
  await claimForm.getByRole('button', { name: '搜索研究证据' }).click()
  await claimForm.getByRole('radio').first().check()
  await claimForm.getByRole('button', { name: '保存主张与证据' }).click()
  await expect(questionCard.getByText('合成窗口实验满足当前成功标准。')).toBeVisible()

  const aiWorkspace = page.getByLabel('AI 应用实验室')
  const opportunityForm = aiWorkspace.getByRole('form', { name: '新建 AI 机会卡' })
  await opportunityForm.getByLabel('机会名称').fill('合成引用定位助手')
  await opportunityForm.getByLabel('问题描述').fill('完全虚构：研究者需要快速定位引用。')
  await opportunityForm.getByLabel('目标用户').fill('使用虚构资料的研究者')
  await opportunityForm.getByLabel('价值假设').fill('减少手工定位耗时。')
  await opportunityForm.getByLabel('可行性假设').fill('复用固定 SourceVersion 字符范围。')
  await opportunityForm.getByRole('button', { name: '保存机会卡' }).click()
  const opportunityCard = aiWorkspace.getByRole('article').filter({ hasText: '合成引用定位助手' })
  await expect(opportunityCard).toBeVisible()
  await opportunityCard.getByRole('button', { name: '开始探索' }).click()
  await expect(opportunityCard.getByText('探索中', { exact: true })).toBeVisible()
  const aiExperimentForm = opportunityCard.getByRole('form', { name: '新建 AI 评测' })
  await aiExperimentForm.getByLabel('评测名称').fill('合成引用完成率评测')
  await aiExperimentForm.getByLabel('评测方法').fill('在 20 条完全虚构任务上测量完成率。')
  await aiExperimentForm.getByLabel('指标').fill('完成率')
  await aiExperimentForm.getByLabel('基线值（可选）').fill('0.6')
  await aiExperimentForm.getByLabel('目标值').fill('0.9')
  await aiExperimentForm.getByRole('button', { name: '保存评测' }).click()
  const aiResultForm = opportunityCard.getByRole('form', { name: '记录 合成引用完成率评测 结果' })
  await aiResultForm.getByLabel('实测值').fill('0.75')
  await aiResultForm.getByLabel('决定').selectOption('stop')
  await aiResultForm.getByLabel('证据摘要').fill('完全虚构：未达到目标，停止当前方案。')
  await aiResultForm.getByLabel('后续任务（可选）').fill('分析合成评测失败样本')
  await aiResultForm.getByRole('button', { name: '记录 Go/Stop' }).click()
  await expect(opportunityCard.getByText(/实测 0.75/)).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'professional-workbench-desktop.png'), fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.getByRole('heading', { name: '专业工作台', exact: true })).toBeVisible()
  const professionalOverflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
  expect(professionalOverflow).toBeLessThanOrEqual(1)
  await page.screenshot({ path: resolve(screenshotRoot, 'professional-workbench-mobile.png'), fullPage: true })

  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/growth')
  await expect(page.getByRole('heading', { name: '前沿与学习', exact: true })).toBeVisible()
  await expect(page.getByText(/不抓取外部资讯/)).toBeVisible()
  const radarWorkspace = page.getByLabel('前沿雷达工作台')
  const radarTopicForm = radarWorkspace.getByRole('form', { name: '新建前沿专题' })
  await radarTopicForm.getByLabel('专题名称').fill('合成离线评测接口')
  await radarTopicForm.getByLabel('领域').selectOption('ai')
  await radarTopicForm.getByLabel('当前综合判断').fill('完全虚构：接口可用于受控本地评测。')
  await radarTopicForm.getByLabel('成熟度').selectOption('experimental')
  await radarTopicForm.getByLabel('处置').selectOption('validate')
  await radarTopicForm.getByLabel('下次复查').fill('2026-10-15')
  await radarTopicForm.getByLabel('主要限制').fill('缺少长期稳定性证据。')
  await radarTopicForm.getByLabel('影响评估').fill('可能缩短合成 AI 场景验证周期。')
  await radarTopicForm.getByRole('button', { name: '保存前沿专题' }).click()
  const radarTopicCard = radarWorkspace.getByRole('article').filter({ hasText: '合成离线评测接口' })
  await expect(radarTopicCard).toBeVisible()
  const signalForm = radarTopicCard.getByRole('form', { name: '为 合成离线评测接口 增加前沿信号' })
  await signalForm.getByLabel('信号摘要').fill('一手公告说明离线评测接口已经发布。')
  await signalForm.getByLabel('内容标记').selectOption('primary_fact')
  await signalForm.getByLabel('发布日期（可选）').fill('2026-09-12')
  await signalForm.getByLabel('检索当前项目的受控来源').fill('离线评测接口')
  await signalForm.getByRole('button', { name: '搜索前沿证据' }).click()
  await signalForm.getByRole('radio').first().check()
  await signalForm.getByRole('button', { name: '保存信号与证据' }).click()
  await expect(radarTopicCard.getByText('一手公告说明离线评测接口已经发布。')).toBeVisible()
  const radarReview = radarTopicCard.getByRole('form', { name: '复核 合成离线评测接口' })
  await radarReview.getByLabel('成熟度').selectOption('early_adoption')
  await radarReview.getByLabel('主要限制').fill('目前仅有完全虚构的受控验证。')
  await radarReview.getByLabel('影响评估').fill('适合进入下一轮本地验证。')
  await radarReview.getByLabel('后续任务（可选）').fill('复核合成前沿信号')
  await radarReview.getByRole('button', { name: '保存复核决定' }).click()
  await expect(page.getByText(/前沿专题复核完成/)).toBeVisible()

  const learningWorkspace = page.getByLabel('学习提升工作台')
  const trackForm = learningWorkspace.getByRole('form', { name: '新建学习方向' })
  await trackForm.getByLabel('方向名称').fill('合成学术英语精读')
  await trackForm.getByLabel('类别').selectOption('english')
  await trackForm.getByLabel('英语重点').selectOption('academic_reading')
  await trackForm.getByLabel('学习目标').fill('独立提取论文主张、证据与限制。')
  await trackForm.getByLabel('当前基线').fill('完全虚构：当前需要逐段回看。')
  await trackForm.getByLabel('成功标准').fill('连续三次练习能完成结构化摘要。')
  await trackForm.getByRole('button', { name: '保存学习方向' }).click()
  const trackCard = learningWorkspace.getByRole('article').filter({ hasText: '合成学术英语精读' })
  await expect(trackCard).toBeVisible()
  const practiceForm = trackCard.getByRole('form', { name: '为 合成学术英语精读 新建练习' })
  await practiceForm.getByLabel('练习名称').fill('精读合成摘要')
  await practiceForm.getByLabel('练习类型').selectOption('reading')
  await practiceForm.getByLabel('计划日期').fill('2026-09-13')
  await practiceForm.getByLabel('练习要求').fill('标注主张、证据与限制。')
  await practiceForm.getByRole('button', { name: '保存练习' }).click()
  const practiceResult = trackCard.getByRole('form', { name: '复盘 精读合成摘要' })
  await practiceResult.getByLabel('练习反思').fill('已找到主张和限制，证据映射仍需加速。')
  await practiceResult.getByLabel('反馈与调整').fill('下一轮先列证据，再写摘要。')
  await practiceResult.getByLabel('自评（可选）').selectOption('3')
  await practiceResult.getByLabel('下一决定').selectOption('adjust')
  await practiceResult.getByLabel('后续任务（可选）').fill('完成下一次合成精读')
  await practiceResult.getByRole('button', { name: '保存练习复盘' }).click()
  await expect(trackCard.getByText(/已找到主张和限制/)).toBeVisible()
  const routineForm = trackCard.getByRole('form', { name: '为 合成学术英语精读 新建习惯' })
  await routineForm.getByLabel('习惯名称').fill('每周合成精读')
  await routineForm.getByLabel('周期').selectOption('weekly')
  await routineForm.getByLabel('目标次数').fill('3')
  await routineForm.getByRole('button', { name: '保存学习习惯' }).click()
  const checkinForm = trackCard.getByRole('form', { name: '记录 每周合成精读 打卡' })
  await checkinForm.getByLabel('日期').fill('2026-09-12')
  await checkinForm.getByLabel('完成次数').fill('2')
  await checkinForm.getByLabel('备注').fill('全部为合成练习记录。')
  await checkinForm.getByRole('button', { name: '记录打卡' }).click()
  await expect(trackCard.getByText(/2026-09-12 · 完成 2 次/)).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'growth-workbench-desktop.png'), fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.getByRole('heading', { name: '前沿与学习', exact: true })).toBeVisible()
  const growthOverflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
  expect(growthOverflow).toBeLessThanOrEqual(1)
  await page.screenshot({ path: resolve(screenshotRoot, 'growth-workbench-mobile.png'), fullPage: true })

  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/context')

  const sourceCard = page.locator('.context-source-list article').filter({ hasText: '合成上下文证据包' })
  await sourceCard.getByLabel('创建新版本').setInputFiles({
    name: 'synthetic-context-evidence-v2.md',
    mimeType: 'text/markdown',
    buffer: Buffer.from('# 合成上下文证据包\n\n完全虚构的受控证据已更新，用于验证不可变来源版本。'),
  })
  await expect(page.getByText(/已创建不可变版本 v2/)).toBeVisible()
  await sourceCard.getByRole('button', { name: '归档' }).click()
  await expect(page.getByText(/来源已归档并从检索中隐藏/)).toBeVisible()
  await page.locator('.context-source-list article').filter({ hasText: '合成上下文证据包' }).getByRole('button', { name: '恢复' }).click()
  await expect(page.getByText(/来源已恢复并重新加入授权检索/)).toBeVisible()

  await page.goto('/system')
  await expect(page.getByRole('heading', { name: '本地备份与恢复' })).toBeVisible()
  await page.getByRole('button', { name: '创建一致性备份' }).click()
  await expect(page.getByText('一致性备份已完成，并已校验数据库与来源文件摘要。')).toBeVisible()
  await page.getByRole('button', { name: '重新校验' }).first().click()
  await expect(page.getByText('备份完整性校验通过。')).toBeVisible()

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/douyin')
  await expect(page.getByRole('heading', { name: '抖音数据' })).toBeVisible()
  await expect(page.locator('.sidebar__brand')).toContainText('DDUP')
  await expect(page.locator('.sidebar__nav-group-label')).toHaveText(/媒体数据/)
  await expect(page.locator('.sidebar__nav-item--child')).toHaveClass(/sidebar__nav-item--active/)
  await page.screenshot({ path: resolve(screenshotRoot, 'media-data-desktop.png'), fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await page.getByRole('button', { name: '打开导航' }).click()
  await expect(page.locator('.mobile-header__brand')).toContainText('DDUP')
  await expect(page.locator('.sidebar__nav-group-label')).toHaveText(/媒体数据/)
  await expect(page.locator('.sidebar__nav-item--child')).toHaveText(/抖音数据/)
  await page.waitForTimeout(450)
  await page.screenshot({ path: resolve(screenshotRoot, 'media-data-mobile.png') })

  await page.keyboard.press('Escape')
  for (const width of [390, 768, 900]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    const mobileNavigation = page.getByRole('navigation', { name: '移动端主要导航' })
    await expect(mobileNavigation).toBeVisible()
    await expect(mobileNavigation.getByRole('link', { name: '今日', exact: true })).toBeVisible()
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
    expect(overflow).toBeLessThanOrEqual(1)
    const targets = await page.locator('.mobile-header button, .mobile-bottom-nav a').evaluateAll((elements) =>
      elements.filter((element) => element.getClientRects().length > 0).map((element) => {
        const box = element.getBoundingClientRect()
        return { width: box.width, height: box.height }
      }),
    )
    expect(targets.length).toBeGreaterThan(0)
    for (const target of targets) {
      expect(target.width).toBeGreaterThanOrEqual(44)
      expect(target.height).toBeGreaterThanOrEqual(44)
    }
    const undersizedText = await page.locator('body *').evaluateAll((elements) => elements.flatMap((element) => {
      const ownText = [...element.childNodes]
        .filter((node) => node.nodeType === Node.TEXT_NODE)
        .map((node) => node.textContent.trim())
        .join(' ')
      if (!ownText) return []
      const rect = element.getBoundingClientRect()
      const style = getComputedStyle(element)
      const inViewport = rect.bottom > 0 && rect.top < innerHeight && rect.right > 0 && rect.left < innerWidth
      if (!inViewport || style.visibility === 'hidden' || style.display === 'none' || Number.parseFloat(style.fontSize) >= 12) return []
      return [{ tag: element.tagName, className: element.className, text: ownText.slice(0, 40), fontSize: style.fontSize }]
    }))
    expect(undersizedText).toEqual([])
  }

  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.reload()
  const skipLink = page.getByRole('link', { name: '跳到主要内容' })
  if (browserName === 'webkit') await skipLink.focus()
  else await page.keyboard.press('Tab')
  await expect(skipLink).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()
  const menu = page.getByRole('button', { name: '打开导航' })
  await menu.click()
  const navigationDialog = page.getByRole('dialog', { name: '完整导航' })
  await expect(navigationDialog).toBeVisible()
  await expect(navigationDialog.locator('a[href]').first()).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(navigationDialog.locator('a[href], button:not([disabled])').last()).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(navigationDialog).toBeHidden()
  await expect(menu).toBeFocused()

  await page.goto('/inbox')
  await expect(page.getByRole('heading', { name: '通用收件箱' })).toBeVisible()
  await page.context().setOffline(true)
  await page.evaluate(() => window.dispatchEvent(new Event('offline')))
  await page.getByLabel('标题').fill('虚构离线草稿')
  await page.getByLabel('内容').fill('仅用于 P1 浏览器验收的虚构内容。')
  await page.getByRole('button', { name: '放入收件箱' }).click()
  await expect(page.locator('.capture-notice')).toContainText('本机草稿')
  const localDraft = await page.evaluate(() => JSON.parse(localStorage.getItem('ddup.capture-draft.v1')))
  expect(localDraft.title).toBe('虚构离线草稿')
  await page.context().setOffline(false)

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/prototype')
  await expect(page.locator('.proto-brand')).toContainText('DDUP')
  await expect(page.locator('.proto-brand img')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'prototype-brand-desktop.png') })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.locator('.proto-mobile-brand')).toContainText('DDUP')
  await expect(page.locator('.proto-mobile-brand img')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'prototype-brand-mobile.png') })
})
