import { resolve } from 'node:path'
import { test, expect } from '@playwright/test'

const screenshotRoot = resolve('../../research/screenshots/workbench-mvp')

test.beforeEach(async ({ context }) => {
  await context.route('**/*', async (route) => {
    const url = new URL(route.request().url())
    if (url.hostname === '127.0.0.1') return route.continue()
    return route.abort('blockedbyclient')
  })
})

test.afterEach(async ({ page }) => {
  await page.evaluate(() => fetch('/__e2e_shutdown', { method: 'POST' })).catch(() => {})
})

test('create, persist and manage synthetic project work items on desktop and mobile', async ({ page }) => {
  test.setTimeout(60_000)
  const crossOriginBootstrap = await page.request.post('/api/v1/session/bootstrap', {
    data: {},
    headers: { Origin: 'https://attacker.example' },
  })
  expect(crossOriginBootstrap.status()).toBe(403)
  await page.goto('/projects')
  await expect(page.getByRole('heading', { name: '项目工作台' })).toBeVisible()
  await expect(page.locator('.sidebar__brand')).toContainText('DDUP')
  await expect(page.locator('.sidebar__nav-group-label')).toHaveText(/媒体数据/)
  await expect(page.locator('.sidebar__nav-item--child')).toHaveText(/抖音数据/)
  await expect(page.getByText('建立第一个项目')).toBeVisible()

  await page.getByRole('button', { name: '新建项目', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: '建立新的项目空间' })).toBeVisible()
  await page.getByLabel('项目名称').fill('合成上下文研究项目')
  await page.getByLabel('目标与说明').fill('完全虚构，用于验证项目创建、持久化与状态迁移。')
  await page.getByLabel('项目模板').selectOption('research')
  await page.getByLabel('开始日期').fill('2026-08-24')
  await page.getByLabel('目标日期').fill('2026-12-31')
  await page.getByRole('button', { name: '创建项目', exact: true }).click()

  const card = page.getByRole('article').filter({ hasText: '合成上下文研究项目' })
  await expect(card).toBeVisible()
  await expect(card.getByText('草稿', { exact: true })).toBeVisible()
  await expect(page.getByText('项目已创建并持久化。刷新或重启后仍会保留。')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'project-workbench-desktop.png'), fullPage: true })

  await page.reload()
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await page.getByLabel('项目名称').fill('合成上下文研究项目 · 已更新')
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  const updatedCard = page.getByRole('article').filter({ hasText: '合成上下文研究项目 · 已更新' })
  await expect(updatedCard).toBeVisible()
  await updatedCard.getByRole('button', { name: '启动项目', exact: true }).click()
  await expect(updatedCard.getByText('进行中', { exact: true })).toBeVisible()

  await updatedCard.getByRole('button', { name: '打开工作项', exact: true }).click()
  const workPanel = page.getByLabel('合成上下文研究项目 · 已更新 工作项')
  await expect(workPanel.getByRole('heading', { name: '合成上下文研究项目 · 已更新', exact: true })).toBeVisible()
  const milestoneForm = workPanel.getByRole('form', { name: '新建里程碑' })
  await milestoneForm.getByLabel('里程碑名称').fill('完成合成开题材料')
  await milestoneForm.getByLabel('目标日期').fill('2026-10-30')
  await milestoneForm.getByRole('button', { name: '保存里程碑' }).click()
  await expect(workPanel.getByLabel('里程碑列表').getByText('完成合成开题材料', { exact: true })).toBeVisible()

  const taskForm = workPanel.getByRole('form', { name: '新建任务' })
  await taskForm.getByLabel('任务名称').fill('整理虚构研究问题清单')
  await taskForm.getByLabel('优先级').selectOption('high')
  await taskForm.getByLabel('目标日期').fill('2026-09-30')
  await taskForm.getByLabel('关联里程碑').selectOption({ label: '完成合成开题材料' })
  await taskForm.getByRole('button', { name: '保存任务' }).click()
  const taskRow = workPanel.getByRole('article').filter({ hasText: '整理虚构研究问题清单' })
  await expect(taskRow).toBeVisible()
  await taskRow.getByRole('button', { name: '纳入计划' }).click()
  await expect(taskRow.getByText('已计划', { exact: true })).toBeVisible()
  await taskRow.getByRole('button', { name: '开始', exact: true }).click()
  await expect(taskRow.getByText('进行中', { exact: true })).toBeVisible()
  await taskRow.getByRole('button', { name: '完成', exact: true }).click()
  await expect(taskRow.getByText('已完成', { exact: true })).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'project-work-items-desktop.png'), fullPage: true })

  const discussionPanel = workPanel.getByLabel('讨论与决策')
  const discussionForm = discussionPanel.getByRole('form', { name: '新建讨论' })
  await discussionForm.getByLabel('聚焦问题').fill('下一阶段是否继续合成研究路线？')
  await discussionForm.getByRole('button', { name: '建立讨论' }).click()
  await expect(discussionPanel.getByText('聚焦讨论已建立。当前只记录人工输入，不调用 AI。')).toBeVisible()
  const entryForm = discussionPanel.getByRole('form', { name: '追加讨论记录' })
  await entryForm.getByLabel('补充观点或依据').fill('虚构验证已证明状态机和持久化路径可用。')
  await entryForm.getByRole('button', { name: '保存记录' }).click()
  await expect(discussionPanel.getByText('虚构验证已证明状态机和持久化路径可用。')).toBeVisible()

  const conversionForm = discussionPanel.getByRole('form', { name: '形成决策与任务' })
  await conversionForm.getByLabel('决策标题').fill('继续合成研究路线')
  await conversionForm.getByLabel('决定内容').fill('继续使用完全虚构的数据完成下一阶段验证。')
  await conversionForm.getByLabel('原因与取舍').fill('先证明闭环，再评审真实数据接入。')
  await conversionForm.getByRole('textbox', { name: '后续任务', exact: true }).fill('补充合成验收场景')
  await conversionForm.getByLabel('优先级').selectOption('high')
  await conversionForm.getByLabel('任务日期').fill('2026-08-24')
  await conversionForm.getByLabel('关联里程碑').selectOption({ label: '完成合成开题材料' })
  await conversionForm.getByLabel('我已核对决定和后续任务，确认写入长期项目记录。').check()
  await conversionForm.getByRole('button', { name: '确认形成决策并创建任务' }).click()
  await expect(discussionPanel.getByText('已按你的明确确认形成正式决策，并在同一事务创建后续任务。')).toBeVisible()
  await expect(discussionPanel.getByText('继续合成研究路线', { exact: true })).toBeVisible()
  await expect(workPanel.getByLabel('任务列表').getByText('补充合成验收场景', { exact: true })).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'project-decision-flow-desktop.png'), fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.getByRole('heading', { name: '项目工作台' })).toBeVisible()
  await expect(updatedCard).toBeVisible()
  await updatedCard.getByRole('button', { name: '打开工作项', exact: true }).click()
  await expect(workPanel.getByText('整理虚构研究问题清单', { exact: true })).toBeVisible()
  await expect(workPanel.getByText('继续合成研究路线', { exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: resolve(screenshotRoot, 'project-workbench-mobile.png'), fullPage: true })

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/inbox')
  await expect(page.getByRole('heading', { name: '通用收件箱' })).toBeVisible()
  const captureForm = page.getByLabel('快速捕获')
  await captureForm.getByLabel('标题').fill('合成研究灵感')
  await captureForm.getByLabel('内容').fill('完全虚构：评估下一阶段的本地恢复路径。')
  await captureForm.getByLabel('关联项目（可选）').selectOption({ label: '合成上下文研究项目 · 已更新' })
  await captureForm.getByRole('button', { name: '放入收件箱' }).click()
  await expect(page.getByText('已进入本地收件箱；不会自动调用 AI、抓取网页或写入长期知识。')).toBeVisible()

  await captureForm.getByRole('button', { name: '链接' }).click()
  await captureForm.getByLabel('标题').fill('合成参考链接')
  await captureForm.getByLabel('http/https 链接').fill('https://example.com/synthetic-reference')
  await captureForm.getByRole('button', { name: '放入收件箱' }).click()
  const textCapture = page.getByRole('article').filter({ hasText: '合成研究灵感' })
  await expect(textCapture).toBeVisible()
  await expect(page.getByRole('article').filter({ hasText: '合成参考链接' })).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'capture-inbox-desktop.png'), fullPage: true })
  await textCapture.getByRole('button', { name: '完成整理' }).click()
  await page.getByRole('tab', { name: '已处理' }).click()
  await expect(page.getByRole('article').filter({ hasText: '合成研究灵感' })).toBeVisible()

  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.waitForTimeout(350)
  await page.screenshot({ path: resolve(screenshotRoot, 'capture-inbox-mobile.png'), fullPage: true })

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '今日', exact: true })).toBeVisible()
  const dailyTask = page.getByLabel('候选任务').getByRole('article').filter({ hasText: '补充合成验收场景' })
  await expect(dailyTask).toBeVisible()
  await dailyTask.getByRole('checkbox', { name: '选择 补充合成验收场景 为今日重点' }).check()
  await page.getByRole('button', { name: '保存今日重点' }).click()
  await expect(page.getByText('今日重点已保存；这里只引用项目任务，不复制任务状态。')).toBeVisible()
  await dailyTask.getByRole('button', { name: '开始', exact: true }).click()
  await expect(dailyTask.getByText('进行中', { exact: true })).toBeVisible()
  await dailyTask.getByRole('button', { name: '完成', exact: true }).click()
  await expect(dailyTask.getByText('已完成', { exact: true })).toBeVisible()
  const reviewForm = page.getByRole('form', { name: '保存日终复盘' })
  await reviewForm.getByLabel('今日总结').fill('完成完全虚构的项目闭环验收。')
  await reviewForm.getByLabel('完成与收获').fill('项目、讨论、任务和收件箱状态一致。')
  await reviewForm.getByLabel('阻塞与原因').fill('真实数据与外部连接仍未授权。')
  await reviewForm.getByLabel('明日第一步').fill('评审下一阶段知识库范围。')
  await reviewForm.getByRole('button', { name: '保存复盘' }).click()
  await expect(page.getByText('日终复盘已保存为你的明确记录，不由 AI 自动改写。')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'today-review-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.waitForTimeout(350)
  await page.screenshot({ path: resolve(screenshotRoot, 'today-review-mobile.png'), fullPage: true })

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/context')
  await expect(page.getByRole('heading', { name: '个人上下文知识库' })).toBeVisible()
  await expect(page.getByText('尚无受控来源')).toBeVisible()
  const sourceForm = page.getByRole('form', { name: '导入 Markdown 来源' })
  await sourceForm.getByLabel('Markdown 文件').setInputFiles({
    name: 'synthetic-context-evidence.md',
    mimeType: 'text/markdown',
    buffer: Buffer.from('# 合成上下文证据包\n\n完全虚构的受控证据，用于验证来源定位、项目过滤与全文检索。'),
  })
  await sourceForm.getByLabel('关联项目（可选）').selectOption({ label: '合成上下文研究项目 · 已更新' })
  await sourceForm.getByRole('button', { name: '导入并建立索引' }).click()
  await expect(page.getByText('Markdown 已写入受控来源目录，并建立可追溯 SourceVersion 与全文索引。')).toBeVisible()
  await expect(page.getByText('合成上下文证据包', { exact: true })).toBeVisible()

  const packageForm = page.getByRole('form', { name: '创建上下文篮' })
  await packageForm.getByLabel('名称').fill('合成方法论论证篮')
  await packageForm.getByLabel('使用目的').fill('聚焦验收固定证据范围与版本追溯。')
  await packageForm.getByRole('button', { name: '创建上下文篮' }).click()
  await expect(page.getByText('已创建空的显式上下文篮；不会自动纳入任何知识。')).toBeVisible()
  await expect(page.getByText('这是一个空篮')).toBeVisible()

  const contextSearch = page.getByRole('form', { name: '统一上下文检索' })
  await contextSearch.getByLabel('检索关键词').fill('完全虚构')
  await contextSearch.getByRole('button', { name: '执行检索' }).click()
  const documentResult = page.locator('.context-results article').filter({ hasText: '合成上下文证据包' })
  await expect(documentResult).toBeVisible()
  await expect(documentResult.getByText(/原文字符/)).toBeVisible()
  await documentResult.getByRole('button', { name: '加入上下文篮' }).click()
  await expect(documentResult.getByRole('button', { name: '已在篮中' })).toBeDisabled()
  await expect(page.locator('.context-package-items').getByText('合成上下文证据包')).toBeVisible()
  await expect(page.getByText('已加入当前上下文篮，范围和版本均已锁定。')).toBeVisible()
  await expect(page.getByText(/过滤在正文返回前执行/).first()).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'context-library-desktop.png'), fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.waitForTimeout(350)
  await page.screenshot({ path: resolve(screenshotRoot, 'context-library-mobile.png'), fullPage: true })

  await page.goto('/')
  await page.keyboard.press('Control+k')
  const palette = page.getByRole('dialog', { name: '全局搜索' })
  await palette.getByLabel('搜索输入框').fill('完全虚构')
  await expect(palette.getByRole('button').filter({ hasText: '合成上下文证据包' })).toBeVisible()
  await palette.getByRole('button').filter({ hasText: '合成上下文证据包' }).click()
  await expect(page.getByRole('heading', { name: '个人上下文知识库' })).toBeVisible()
  await expect(page.locator('.context-results article').filter({ hasText: '合成上下文证据包' })).toBeVisible()

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/douyin')
  await expect(page.getByRole('heading', { name: '抖音数据' })).toBeVisible()
  await expect(page.locator('.sidebar__brand')).toContainText('DDUP')
  await expect(page.locator('.sidebar__nav-group-label')).toHaveText(/媒体数据/)
  await expect(page.locator('.sidebar__nav-item--child')).toHaveClass(/sidebar__nav-item--active/)
  await page.screenshot({ path: resolve(screenshotRoot, 'media-data-desktop.png'), fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await page.getByRole('button', { name: '打开导航' }).click()
  await expect(page.locator('.mobile-header__brand')).toContainText('DDUP')
  await expect(page.locator('.sidebar__nav-group-label')).toHaveText(/媒体数据/)
  await expect(page.locator('.sidebar__nav-item--child')).toHaveText(/抖音数据/)
  await page.waitForTimeout(450)
  await page.screenshot({ path: resolve(screenshotRoot, 'media-data-mobile.png') })

  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/prototype')
  await expect(page.locator('.proto-brand')).toContainText('DDUP')
  await expect(page.locator('.proto-brand img')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'prototype-brand-desktop.png') })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.locator('.proto-mobile-brand')).toContainText('DDUP')
  await expect(page.locator('.proto-mobile-brand img')).toBeVisible()
  await page.screenshot({ path: resolve(screenshotRoot, 'prototype-brand-mobile.png') })
})
